root: true
extends:
  - airbnb
  - vue
plugins:
  - import
rules:
  space-before-function-paren:
    - 1
    - "never"
  semi:
    - 1
    - "always"
  no-multiple-empty-lines:
    - 1
    - max: 3
  arrow-parens:
    - 1
    - "as-needed"